on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_type }}
  cancel-in-progress: true
jobs:
  publish:
    env:
      HUGO_VERSION: 0.115.1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: none
      actions: none
      checks: none
      discussions: none
      id-token: none
      issues: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Verify Installed Node
        run: node --version
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Verify Installed pnpm
        run: pnpm --version
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          cache: false
          check-latest: true
      - name: Verify Installed Go
        run: go version
      - name: Install Hugo
        run: |
          curl -SfL https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.tar.gz | tar -xzvf - hugo
          export PATH="$PATH:$(pwd)"
      - name: Verify Hugo Installation
        run: hugo env
      - name: Build
        run: make build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: xeptore-blog
          directory: ./public
          wranglerVersion: "3"
